### ISSUE TITLE
Upload error for Splash image

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#101]
I'm getting this when I try to upload a splash image: "Error moving file to upload dir. Check permissions?" Could this be because I'm working from home?

**Comment by sethjohnson1** [comment]
No, I don't think I ever set the proper permissions on that directory. Should be working now!

**Comment by CenterNancy** [comment]
Hmm - now getting an internal error message ("An Internal Error Has Occurred.") when I submit first screen, before getting to the upload image screen...

**Comment by sethjohnson1** [comment]
Oops I broke it cleaning up old files. It works again. Let me know if
anything else is afoul.
