### ISSUE TITLE
Update verbiage in e-mails

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#102]
They go straight to Spam at the moment, probably just need to update the text a little bit and add a small explanation at the end of them

**Comment by CenterNancy** [comment]
Tried to create an e-mail account but didn't receive the verification e-mail, either in inbox or junk/spam... Tried it twice.

**Comment by sethjohnson1** [comment]
Hmm . . I just have no idea. I tested with a hotmail account and it sent the e-mail fine (still went to Junk though). Try going here:

http://iscout.bbcw.org/users/resend_verification

And see what happens

**Comment by CenterNancy** [comment]
Well there it is! That worked. Also no idea why registration and this didn’t work for me yesterday. Hopefully it was “operator error” on my part…

Nancy

**Comment by sethjohnson1** [comment]
Ok good. I am going to see if I can get them to stop going straight to Spam.

**Comment by sethjohnson1** [comment]
Well I removed the shortener and they still just go straight to junk. Doh!
I think we just need more there. Whatever I wrote even sounds like Spam to
me...

**Comment by CenterNancy** [comment]
I do have that e-mail text and html draft on my list, hopefully get to it this weekend

Nancy

On Mar 14, 2015, at 12:37 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Well I removed the shortener and they still just go straight to junk. Doh!
I think we just need more there. Whatever I wrote even sounds like Spam to
me...

On Fri, Mar 13, 2015 at 8:30 AM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Well there it is! That worked. Also no idea why registration and this
> didn't work for me yesterday. Hopefully it was "operator error" on my part...
>
> Nancy
>
> From: sethjohnson1 [mailto:notifications@github.com]
> Sent: Friday, March 13, 2015 8:25 AM
> To: sethjohnson1/qr-pub
> Cc: Nancy McClure
> Subject: Re: [qr-pub] Update verbiage in e-mails (#102)
>
>
> Hmm . . I just have no idea. I tested with a hotmail account and it sent
> the e-mail fine (still went to Junk though). Try going here:
>
> http://iscout.bbcw.org/users/resend_verification
>
> And see what happens
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/sethjohnson1/qr-pub/issues/102#issuecomment-78994303>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/qr-pub/issues/102#issuecomment-78996911>.
>

-

**Comment by CenterNancy** [comment]
Here's revision for text I'm thinking of; tell me what you think and then I'll work on making it pretty...

Hi [name],
Thanks for creating an iScout account! Just click the link below within 24 hours to validate your account and log in. Then as you tour you can comment and rate, earn postcards, and share the fun!
[verification link]
If you did not create an account, simply delete this e-mail, OR, try out iScout for one session and let us know what you think! [I'm not sure what "The provided link will authenticate the account for one session" means - is that for an account that would "expire" or something?]

**Comment by CenterNancy** [comment]
How about an e-mail to look like this? (Of course once I drew this up I realized someone will hang me for not including the main BBCW logo - do you think I better rework?)
![screen shot 2015-03-15 at 7 17 33 pm](https://cloud.githubusercontent.com/assets/9464698/6659300/2e509592-cb48-11e4-8e77-b1f7c125c05a.png)

**Comment by sethjohnson1** [comment]
It looks really nice and my first test DO NOT go to Spam! We don't need the logo here, the emails need to be really lightweight

**Comment by CenterNancy** [comment]
Wow, really? That's cool. I'll send you the html file and the image, although maybe we don't want that one here either; we could just "sign" it iScout / http://iscout.bbcw.org/

**Comment by CenterNancy** [comment]
My test of e-mail revised by following tutorial (http://webdesign.tutsplus.com/tutorials/what-you-should-know-about-html-email--webdesign-12908) seems to work; tested through MailChimp e-mail built with code; checked in Outlook and Hotmail on regular display and iPhone.

**Comment by sethjohnson1** [comment]
Cool I plan to get this updated tomorrow. do you just want to e-mail me the
updated HTML?

**Comment by CenterNancy** [comment]
Will do!

Nancy

On Mar 22, 2015, at 10:34 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool I plan to get this updated tomorrow. do you just want to e-mail me the
updated HTML?

On Sun, Mar 22, 2015 at 7:54 PM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> My test of e-mail revised by following tutorial (
> http://webdesign.tutsplus.com/tutorials/what-you-should-know-about-html-email--webdesign-12908)
> seems to work; tested through MailChimp e-mail built with code; checked in
> Outlook and Hotmail on regular display and iPhone.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/qr-pub/issues/102#issuecomment-84747339>.
>

-

**Comment by CenterNancy** [comment]
See if these work now…

Nancy

**Comment by sethjohnson1** [comment]
Where are they?

**Comment by CenterNancy** [comment]
Sorry! I'll e-mail them to sethj@centerofthewest.org<mailto:sethj@centerofthewest.org> right now

Nancy

On Mar 23, 2015, at 7:23 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Where are they?

On Mon, Mar 23, 2015 at 7:47 AM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> See if these work now...
>
> Nancy
>
> From: sethjohnson1 [mailto:notifications@github.com]
> Sent: Sunday, March 22, 2015 10:35 PM
> To: sethjohnson1/qr-pub
> Cc: Nancy McClure
> Subject: Re: [qr-pub] Update verbiage in e-mails (#102)
>
> Cool I plan to get this updated tomorrow. do you just want to e-mail me
> the
> updated HTML?
>
> On Sun, Mar 22, 2015 at 7:54 PM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
> wrote:
>
> > My test of e-mail revised by following tutorial (
> >
> http://webdesign.tutsplus.com/tutorials/what-you-should-know-about-html-email--webdesign-12908)
>
> > seems to work; tested through MailChimp e-mail built with code; checked
> in
> > Outlook and Hotmail on regular display and iPhone.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sethjohnson1/qr-pub/issues/102#issuecomment-84747339>.
>
> >
>
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/sethjohnson1/qr-pub/issues/102#issuecomment-84804541>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/qr-pub/issues/102#issuecomment-85002146>.
>

-

**Comment by CenterNancy** [comment]
K try now at your work e-mail

**Comment by sethjohnson1** [comment]
I think we're done here. I changed "find this interesting" bit to "thought you might like this" because otherwise "interesting" was pushed to another line and it looked kind of silly. Test 'em all out - if you're happy feel free to close the issue!

**Comment by CenterNancy** [comment]
Other than one minor English-Nazi suggestion I think they look good! That is, in "I'm having a great time...and thought I'd share it..." can we change "thought I'd" to "want to" because we use the word "thought" again in the next sentence? 

Adding sender handle to subject line in sharing is nice, so if they just forward without changing subject, that's be in there for the recipient.

Tests to hotmail work well, go to inbox. Sharing to Facebook works well.

Tests to centerofthewest@gmail.com: account verification went to spam :( but sharing e-mail and password reset e-mail went to inbox (without me marking the first one as safe). Go figure...

**Comment by sethjohnson1** [comment]
I updated the text per your changes, not sure what to do about gmail Spam. . . I will think about it for awhile
