### ISSUE TITLE
Square-ish intro graphic

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#104]

**Comment by CenterNancy** [comment]
Jess's graphic is now in place; however, she and Desiree wonder if "we" (that would be you if this is even possible...) can make it so at mobile screen width the left side of graphic could stay aligned to left edge of the logo's base bar. Probably be easiest to view on phone screen to see what I mean, or this:
![logo-image-alignment](https://cloud.githubusercontent.com/assets/9464698/6648040/b0de8668-c99a-11e4-8cb0-0b4d38f5283c.jpg)

**Comment by sethjohnson1** [comment]
I really like the graphic. Do we want to change "Want to learn more about this object?"? I don't dislike it, but sometimes it might not really be an object, and I'd love to get the word "fun" in there somewhere. 

Anyway, with regards to that change, I think we can get close. Have a look now and let me know if I am understanding the request

**Comment by CenterNancy** [comment]
Yep, you nailed it! The style guide police will be happy. :)
Yes, we should ponder better and more engaging wording I guess...

**Comment by CenterNancy** [comment]
How about any of these?
-Have some fun and begin your journey!
-Begin the journey and have some fun!
-Have some fun and learn more!
-Follow the fun with iScout!
-Follow the fun and learn more!
-Learn more and enjoy the journey!
-iScout is your guide for a fun tour!

**Comment by CenterNancy** [comment]
Revised: http://iscout.bbcw.org/
