### ISSUE TITLE
Virtual postcards

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#105]
I would like to do this as long as I can get some help designing the postcards. One idea would be to make one for each museum. Also, I thought we could leave a blank space for their name and use some image manipulation to add it to the certificate

**Comment by sethjohnson1** [comment]
Like anything, this got complicated in a hurry. Adding a name imposes some serious limitations for social sharing, don't really want to use a pop-up, simply sharing the postcard page won't work unless we manipulate the URL somehow, not sure how much people will really even care/use these. I think I will roll forward and keep it very simple, maybe the URL should be this crazy-endcoded . . thing . . that determines how many postcards to show and even their name (?)  Going to think for awhile...

**Comment by sethjohnson1** [comment]
Ah yes, quite simple really. I will URL encode a deflated, encrypted JSON array with all the necessary info. It's going to be one meal of a URL, but it will work...

**Comment by CenterNancy** [comment]
Would it be easier (or harder), to have the sharing capability for an individual postcard when earned? A pop-up when you earn it, with a "share" button that would only share that postcard. That would not need the name on it because they would share it on their own social channel.
Then, on the My Postcards page, you would have all earned with the dotted outline/lock (I love that) for yet-to-earn one. This page could have the name like a certificate, but the sharing would be done with the individual cards and not this tally page.
Just an idea that I have no idea whether it's feasible or not!

**Comment by sethjohnson1** [comment]
well... my brain went down many crooked paths, eventually I decided to make
it as complicated as possible. I think you're right, the popup should have
a share link - which will include this crazy long - yet shortened - URL.

**Comment by sethjohnson1** [comment]
made a bunch of changes to this, just need some cool graphics now!

**Comment by CenterNancy** [comment]
An option for postcard based on web ads. Let me know what you think, Seth.
![ao-postcard-option2](https://cloud.githubusercontent.com/assets/9464698/6998802/b1d07d0c-dbaa-11e4-84a9-dff066cdd797.jpg)

**Comment by sethjohnson1** [comment]
I like it. We should probably get the URL to the site and also maybe
mention Cody, WY.

**Comment by CenterNancy** [comment]
Oh, of course! I’ll revise.

Nancy

**Comment by CenterNancy** [comment]
Postcard revision for review...
![ao-postcard-option3](https://cloud.githubusercontent.com/assets/9464698/7060181/a85b068e-de39-11e4-90b8-c56318f58c63.jpg)

**Comment by sethjohnson1** [comment]
Oh yeah that looks nice!

**Comment by CenterNancy** [comment]
Okay – almost caught up on a couple pressing projects so should get rest done soon (…no, really…)

Nancy

**Comment by CenterNancy** [comment]
2 more. We're gonna need 6, right? so you have an even number for the "My postcards" page.
![bb-postcard](https://cloud.githubusercontent.com/assets/9464698/7078016/bd38546e-ded2-11e4-8b41-784855d22e8c.jpg)
![eagle-postcard](https://cloud.githubusercontent.com/assets/9464698/7078019/c0887306-ded2-11e4-87ca-d45ed2348d92.jpg)

**Comment by sethjohnson1** [comment]
Yes 6 total is perfect, these look great. The only thing that I thought
perhaps "Share" in the URL box should also entice the potential visitor, I
don't know... Can it be something like "Explore & Share" (or some other
exciting work) Am I talking crazy?

Thanks for all your help so far.

**Comment by CenterNancy** [comment]
![ao-postcard](https://cloud.githubusercontent.com/assets/9464698/7080009/dae9c216-dee8-11e4-93eb-39ddfb1eebf1.jpg)
![bb-postcard](https://cloud.githubusercontent.com/assets/9464698/7080010/ddef53cc-dee8-11e4-8d86-043f62b38681.jpg)
![eagle-postcard](https://cloud.githubusercontent.com/assets/9464698/7080012/e148956a-dee8-11e4-9ece-bee689e945c4.jpg)

**Comment by sethjohnson1** [comment]
Yes! Thank you! Do you want me to use these 800x600 or larger ones?

**Comment by CenterNancy** [comment]
I guess I was thinking the 800 x 600 like a standard physical postcard... Do you think larger would be better?

**Comment by sethjohnson1** [comment]
No sounds good to me. I will get these added and then check my iPad and see
what they look like in the popup

**Comment by sethjohnson1** [comment]
Ok check it out now - I made some small things, let me know of any changes
you can think of

**Comment by CenterNancy** [comment]
I love it! - and I think your text is great.

**Comment by CenterNancy** [comment]
![tipi-postcard](https://cloud.githubusercontent.com/assets/9464698/7080597/206bcd3a-def2-11e4-8ff0-9fdc4dcba818.jpg)

**Comment by CenterNancy** [comment]
![traffic-postcard](https://cloud.githubusercontent.com/assets/9464698/7081022/ced3a4e6-def8-11e4-848a-7ae4f77f1652.jpg)

**Comment by CenterNancy** [comment]
![scout-postcard](https://cloud.githubusercontent.com/assets/9464698/7081417/b4df7cee-defe-11e4-8894-7d69c13613bc.jpg)

**Comment by sethjohnson1** [comment]
great work! I added them all earlier today you can check it out and feel free to close the issue. As we get more items we may consider lowering the threshold at which one must visit to gain postcards - right now its 80%

**Comment by CenterNancy** [comment]
Yes, happy with the whole postcard part. Pretty decent teamwork I'd say :)
