### ISSUE TITLE
overlay notifications

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#108]
After spending the better part of what feels like eternity on scorecard and postcard, I am going to add some popup overlays to notify people to actually use it.

**Comment by sethjohnson1** [comment]
Mostly done, Nancy can you help with the verbiage? Also, there is a glitch where the "old" popups show if revisiting the page, I know exactly why and how to fix it but I have to go now :)

**Comment by CenterNancy** [comment]
Sure, I can help with that. Where would I access each of the popups to see the verbiage?

Nancy

**Comment by CenterNancy** [comment]
Some star image options...
![1-star_lost-greenhorn](https://cloud.githubusercontent.com/assets/9464698/6861388/033d6b58-d3fb-11e4-868e-fea7944d0d2f.png)
![2-star_beaded-trucker-hat](https://cloud.githubusercontent.com/assets/9464698/6861391/06c9ecd8-d3fb-11e4-9fb1-9b652bb46e30.png)
![2-star_salem](https://cloud.githubusercontent.com/assets/9464698/6861393/0c5ceb0a-d3fb-11e4-9fde-2c4e25a632d4.png)
![3-star_bb-poster](https://cloud.githubusercontent.com/assets/9464698/6861394/0ebc3662-d3fb-11e4-827e-56d15b993073.png)
![3-star_bear-104](https://cloud.githubusercontent.com/assets/9464698/6861396/10c592c8-d3fb-11e4-8b82-2368db37a80e.png)
![4-star_ducksfoot-pistol](https://cloud.githubusercontent.com/assets/9464698/6861397/1318e05c-d3fb-11e4-9d1d-0775b9ba14ac.png)
![5-star_scout](https://cloud.githubusercontent.com/assets/9464698/6861401/1dfa4736-d3fb-11e4-89fc-67184050da1e.png)

**Comment by CenterNancy** [comment]
For overlay text, what about this slight shortening (below)? I think we can eliminate "another" because they'll get it after the first one, for which "another" doesn't really apply. Could we also add a little transparency to the "Not now" button to make it recede just a little?
Text tweak:
You’ve visited enough stops to earn an iScout Star! 
Check your Score Card for your official title, some free advice, and the postcards you’ve unlocked!

**Comment by sethjohnson1** [comment]
Sure no prob on any of that. I loaded the circles. I like all of them! I
think we'll make some way to access them from the score card too because on
the popups once you close it you never see it again. People might want to
access them like little badges...?

Also, there is some alternate text for the five star popup instead of
"you've visited enough to earn an iscout star" - let me know what you'd
like that to be.

**Comment by CenterNancy** [comment]
They are fun to make, so if the perfect image/object comes to mind for any of the levels of stars, let me know! Yes, we'll have to think of a good pinnacle sort of text for the final one...
Think I'll crash for tonight!

**Comment by sethjohnson1** [comment]
ok cool. Check it out and let me know, close it when ready

**Comment by CenterNancy** [comment]
Pretty cool! I see a couple things: The old one with only the one orange star and not gray shows up for the 1st star rank; and no circle image showed up on the 5th. BTW, what do you think of the orange on the pink sky on the 5th image – are the colors a little jarring together?

How about for the 5-star popup:

Great scouting!
You've earned our Top iScout Rank with all five stars
Take one last look at your Score Card, your postcards, and share your achievement!

Nancy
