### ISSUE TITLE
Fix code generating

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#109]
Start at number 300. Do we want to start each museum with a number? Whitney would have to be 1 for Acoustiguide to match up, CFM already claimed '2'

**Comment by sethjohnson1** [comment]
oh that was easy, already starts at last number, just updated first template to be "300" and we're done. We will have to go back and fix the other ones, sorry...

**Comment by CenterNancy** [comment]
Updated all template numbers. To keep it from getting unnecessarily complicated I didn't assign the other three museums, library, and garden spaces a specific span, just started them at 301 and continued. Can change if you think we should but if I remember right we decided not to worry about that...
