### ISSUE TITLE
Tweaks to side panel menu

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#110]
I know!!!! You'll hate me for opening an issue this late but it's just an enhancement! In the side panel menu, could we make "Score Card" "My Score Card" to go with "My Postcards"
Then we should make capitalization consistent (see below), and what do you think about reordering the items as follows:
About iScout
Browse Stops
My Score Card
My Postcards
Give Feedback
Close Panel
And just to be more of a pain :), I think we need one smallish image on the About iScout page. I'll ponder

**Comment by sethjohnson1** [comment]
No problem at all, I intentionally created the menu in such a way that those changes took about 2 min. I agree we need a pic on About page, so feel free to ponder and let me know what you come up with

**Comment by sethjohnson1** [comment]
Ok check out the image and let me know what you think. I tried text-align justify and it looks best to me, but not sure what you think

**Comment by CenterNancy** [comment]
Yes! I love that!

Nancy

**Comment by sethjohnson1** [comment]
Cool - feel free to close the issue!

**Comment by CenterNancy** [comment]
One tiny thing – could you capitalize the “Stops” on Browse stops?

Nancy

**Comment by sethjohnson1** [comment]
done

**Comment by CenterNancy** [comment]
Thanks
