### ISSUE TITLE
Google OAuth broken

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#111]
Will need to completely rewrite OAuth as they seem to have changed their spec on March 21. Ugh....

**Comment by CenterNancy** [comment]
What??

Nancy

**Comment by sethjohnson1** [comment]
In other words: Logging in with Google no longer works because they changed something on their end.

**Comment by sethjohnson1** [comment]
final task will be to clean up code scattered all over the place also fix composer.json
