### ISSUE TITLE
popups close on iOS with external link

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#114]

**Comment by sethjohnson1** [comment]
The solution seems to be the a delayed, triggered click to the popup with a blank link on the page.. No other suggestions worked so I cooked that up... Need iPhone testing

**Comment by CenterNancy** [comment]
Yes! They stay open now on iPhone

Nancy

On Mar 27, 2015, at 10:04 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


The solution seems to be the a delayed, triggered click to the popup with a blank link on the page.. No other suggestions worked so I cooked that up... Need iPhone testing

-

**Comment by sethjohnson1** [comment]
yay!
