### ISSUE TITLE
Show circles on score card

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#115]

**Comment by sethjohnson1** [comment]
Nancy let me know what you think - figured we might as well capitalize on all the wacky randomness.

**Comment by CenterNancy** [comment]
Yeah, I like that! Do you think I should take the logo and stars off the "empty" circle and make the lock bigger? I like them on there but you can't really see them well on the small screen...

**Comment by sethjohnson1** [comment]
I like it the way it is, and if people are curious they will tap on it

**Comment by CenterNancy** [comment]
Sound good!

Nancy
