### ISSUE TITLE
Images without captions don't center

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#134]
Is there a way to make images in blog posts that don't have captions center in iScout (like images that do have caption?

**Comment by sethjohnson1** [comment]
Probably some CSS class thing. Can you provide an example?

**Comment by CenterNancy** [comment]
Here's one: http://iscout.bbcw.org/templates/view/51
2nd image doesn't have a caption and it is floating left

**Comment by sethjohnson1** [comment]
Ah ok. Check it out now - I also decided not to make the images so small. I
figured well... I like pictures. It also looks better on a mobile device
(IMHO). Let me know what you think and feel free to close the issue when
ready.

**Comment by CenterNancy** [comment]
Perfect - yes especially nice on phone/tablet! Thank you.
