### ISSUE TITLE
Scorecard

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#37]
the popup display is out of view on small device, basically, the whole idea of the popup should be scrapped.
A separate page sounds better, and could possibly be combined with "offline category view"

**Comment by sethjohnson1** [comment]
Most of the Scorecard logic is written, the basic style is done - but for now it just doesn't seem to fit anywhere

**Comment by sethjohnson1** [comment]
This will just be added to side menu as a separate page. Easy..

**Comment by sethjohnson1** [comment]
"easy" was not exactly it. Just need to show Nancy how to update rankings and quotes (if she wants to, otherwise it's fine)

**Comment by CenterNancy** [comment]
Absolutely!

Nancy

**Comment by CenterNancy** [comment]
Hey Seth, if you have time to show me this today I’d like to see what you already have in there; I thought of a few to add…

Nancy
