### ISSUE TITLE
enter code doesn't work at all after blindly copy/pasting it into jquery mobile header

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#70]
wow, that's annoying - apparently was not tested in the slightest

**Comment by lloydjcenterofthewest** [comment]
I didn't know this was working at all, where was the code?



On Jan 18, 2015, at 11:25 AM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


wow, that's annoying - apparently was not tested in the slightest

-

**Comment by sethjohnson1** [comment]
many, many reasons why it never would've worked - the most basic was that the same form ID was still being drawn in the CodePopup above it, so therefore the form data would always be empty. Also didn't work in Android (impossible to submit form), also didn't work when changing templates with next and prev buttons, also your "submit" button had "type" declared twice in the array, which meant it was a hidden input that did absolutely nothing.
