### ISSUE TITLE
admin interface instructions

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#77]

**Comment by CenterNancy** [comment]
E-mailing Seth PDF of draft instructions. Probably kind of rough cuz didn't re-read; but would like input if you have any.

**Comment by sethjohnson1** [comment]
Wow that is good. The Chuckwagon example is awesome. Some things:

1. The AcoustiGuide template is really a "small youTube template with extra fields" - we can think of a better name and possibly ignore instructions on it for now

2. 'Get info' button shouldn't say "no need to worry what all this means" but something like "make sure it resembles what you intend"

3. overall it looks really awesome I assume we can update the URL, etc. (issue #83 , for example)

**Comment by CenterNancy** [comment]
Thanks! Yes, we can make any changes still. Just sent PDF because seems like the images shift weird on the Word doc and I wanted them to stay put!
Oops on #4 :)

**Comment by CenterNancy** [comment]
Would "Nowhere" be used as a location for anything other than the Intro page? I can't think of another example at the moment, but it could be used inside a string I suppose (not for the start since the user needs to see the code for it in a museum/garden area, etc.)

**Comment by CenterNancy** [comment]
Revision

Nancy

**Comment by sethjohnson1** [comment]
Nowhere can be used anywhere you don't want to show up in the global browse
navigation - typically an intro page. The idea is that this can also
potentially be used for special events or something where it doesn't make
sense for it to be part of the global nav.

**Comment by CenterNancy** [comment]
K - thanks

Nancy

**Comment by CenterNancy** [comment]
Does this make sense for the instructions?
Choose your “Location” from its dropdown
   - All museums, library, garden areas, or nowhere (used for our intro page, for “stops” that don’t need to show up in the “Browse stops” navigation, e.g. a special event used as an entry point for a topic)

**Comment by CenterNancy** [comment]
I’ve put the instructions draft in this folder now: \\bbhclan.org\share\projects\Current\Web Site\NM iScout Stuff<file:///\\bbhclan.org\share\projects\Current\Web%20Site\NM%20iScout%20Stuff>

Nancy

**Comment by sethjohnson1** [comment]
Cool. I think we're ready to distribute it and schedule a training for those who want to attend. We can update and tweak as needed once people begin looking at it

**Comment by CenterNancy** [comment]
Sounds good!

Nancy

On Mar 3, 2015, at 6:02 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool. I think we're ready to distribute it and schedule a training for those who want to attend. We can update and tweak as needed once people begin looking at it

-

**Comment by CenterNancy** [comment]
Closing, but will revise if needed once people start using it. A copy is in this location: \\bbhclan.org\share\projects\Current\Web Site\iScout Admin Instructions
