### ISSUE TITLE
BBCW logo looks strange, like the spaces on either side of bottom bar are not transparent.

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#81]

**Comment by sethjohnson1** [comment]
Thanks for adding this, you're right it's YASTPG (Yet Another Slapped-Together Piece of Garbage) that needs to be fixed.

**Comment by CenterNancy** [comment]
So I guess I added it correctly - partly added to get the hang of GitHub :)

**Comment by sethjohnson1** [comment]
Yeeeah! You are "official". Ok check it now, I at least just made the sides white. I don't think we need opacity for the bar - although we could if we wanted. It uses the border element to draw that, so we'd need to do something like this:
http://stackoverflow.com/questions/4062001/css3-border-opacity

**Comment by CenterNancy** [comment]
White sides would work I think, except on my screens it is ever so slightly too high, so that the tan bar shows below it. Could its vertical position be shifted down a pixel or two to compensate? Not to be nitpicky or anything :)

**Comment by sethjohnson1** [comment]
Sounds like something for your first commit :)

**Comment by CenterNancy** [comment]
☺ - sure if you can walk me through that sometime

Nancy

**Comment by CenterNancy** [comment]
Looks good this morning. Tested moving down a pixel and that's too far. I'll look on my Mac at home one more time before closing...

**Comment by CenterNancy** [comment]
Okay - this is what the logo looks like on my Mac laptop. Since we intend this to be mainly for mobile/tablet, does this matter?
![screen shot 2015-01-26 at 5 39 43 pm](https://cloud.githubusercontent.com/assets/9464698/5911422/a337f4ae-a582-11e4-9aeb-450decfd6239.png)

**Comment by sethjohnson1** [comment]
The "proper" fix will have to wait - but you're right the display is inconsistent and a bit sloppy. I am leaving it open and tagging it an enhancement

**Comment by sethjohnson1** [comment]
ok I got it as close as I can. Looks good to me (although the discerning eye can still see a smidge of grey)
