### ISSUE TITLE
Suggestions for iScout (identified while writing instructions for building/stringing together templates)

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#83]
1. Should we standardize name of each template? Suggest: 
    - "Big image" becomes "Splash image"
    - "AV page" becomes "Video" (unless this will eventually include audio files...?)
    - "Virtual Gallery" - just change to lowercase on "gallery" for consistency
    - "Web article" becomes "Blog post" (I know we were avoiding "blog" but this is the most descriptive and goes with the "Type" in the templates list)
    - These changes make things more consistent with terms on List Templates screen (splash, video, vgal, blog, ag)

2. In add splash, change "upload jpg image, 1000x1000 works nice" to "Upload jpg image, 1000px wide or less works best"
3. In add video, change "Youtubeid" field label to "YouTubeID" (I know, style/usage nerd here)
4. In add blog, change "Blogid" field label to "BlogID"
5. In add vgal, change "Vgalid" field label to "VgalID"
6. In the templates list, change the "Id" column label to "ID"

7. Without knowing how much work this would take or if there are specific reasons not to, would it be possible for the "Submit" button to hide itself at the same time that "The asset has been saved." appears at the top? I wonder if people will get confused and keep clicking "Submit" thinking nothing happened...

8. On blog posts, can the view wrap text on images, or center the images instead of left aligning them?

**Comment by sethjohnson1** [comment]
1-6 no problem. For item 7, it now redirects back to the user's list of templates after saving. This is more "normal" behavior I just didn't have it there for testing. For item 8 I have centered them. Text wrapping doesn't work consistently in this scenario (I can demo it for you sometime if you'd like to see what I mean). The wrapping is mostly of concern on larger screens - which isn't our main target audience anyway

**Comment by CenterNancy** [comment]
Oh right - the small screens; duh! Centered makes me happy though, thanks :)

**Comment by sethjohnson1** [comment]
no prob. Just realized I missed a few things here too, they will be done though

**Comment by CenterNancy** [comment]
I now really get the awesomeness of github for tracking and communicating all this stuff! I love it :)

**Comment by sethjohnson1** [comment]
Yes I am going to force other people to sign up eventually. Anyway this is done now - I did some quick JS to hide the submit button - nothing fancy but it does help people understand what's going on (especially the vgal which can take some time to submit)
