### ISSUE TITLE
Format for Audio Guide iscout

### ISSUE THREAD

**Issue by ewillywilson** [sethjohnson1/qr-pub#88]
Is there a way instead of having Title: Date:  etc. to just do a line credit at the top:

Eg. Albert Bierstadt (b-d). Yellowstone Falls. Ca. 1881  (top line all bold, titled also italicized)
     oil on canvas, 44.25 x 30.5 in. Gift of Mr. and Mrs. Lloyd Taggart

Then instead of synopsis you can say transcript

Should we put a tag line on: Audio courtesy of Acoustiguide   ?

**Comment by CenterNancy** [comment]
Shouldn't the credit line also include the accession number at the end?

**Comment by ewillywilson** [comment]
Sure, yes. I don’t think addition of that will be problematic if Seth is able to set up a feature for me to block write it out.

-E



Emily Wilson
Curatorial Assistant
Whitney Western Art Museum

O 307-578-4051
Buffalo Bill Center of the West
720 Sheridan Avenue, Cody, WY 82414
emilyw@centerofthewest.org<mailto:emilyw@centerofthewest.org>
[the_Center_sized]

**Comment by sethjohnson1** [comment]
Ok Emily check out the link I sent you and let me know

**Comment by sethjohnson1** [comment]
as per Emily "looks good, add Acoustiguide mention at the end "
