### ISSUE TITLE
Make a video gallery

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#90]
Not sure if this is the best option, perhaps just downloading the videos is better - but then how to play them easily in web interface?

**Comment by sethjohnson1** [comment]
Considering what Ashley wants to do, this is not the right solution. Need a video gallery instead (local video files I guess)

**Comment by CenterNancy** [comment]
Could something like this just be done through a playlist set up on YouTube? With the template just taking you to the first video as an entry point to the playlist?

**Comment by sethjohnson1** [comment]
The problem is that the YouTube videos cannot play in their entirety - we
just need clips. I don't think YouTube can do that.

**Comment by sethjohnson1** [comment]
We're just going to submit the group of videos in a blog post. Yay I love simple solutions.

**Comment by CenterNancy** [comment]
Tried this and videos won't resize automatically on mobile. Giving up for today in frustration

**Comment by CenterNancy** [comment]
The below trick from http://avexdesigns.com/responsive-youtube-embed/ seems to work for the blog post (to have videos resize as screen size changes), but not when the post is viewed in iscout.
CSS:
.video-container {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 30px; height: 0; overflow: hidden;
}
 
.video-container iframe,
.video-container object,
.video-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

HTML:
<div class="video-container">
         <iframe width="420" height="315" src="https://www.youtube.com/embed/xRXXxQ1OuDc?rel=0" frameborder="0" allowfullscreen></iframe>
</div>

**Comment by sethjohnson1** [comment]
Yeah the API doesn't send over the inline CSS stuff. What is the template
ID? I will do some tests - I should be able to use that same CSS in iScout
and make it work.

**Comment by sethjohnson1** [comment]
Ok I found it, check it now.

**Comment by CenterNancy** [comment]
Awesome. THANK YOU!

Nancy

**Comment by sethjohnson1** [comment]
I think we're all set, just keep in mind you'll want to use the same class names if you intend to use it again

**Comment by CenterNancy** [comment]
I should've named more specifically then right? I was just in a hurry to see if it would work at all

Nancy

On Apr 8, 2015, at 4:47 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we're all set, just keep in mind you'll want to use the same class names if you intend to use it again

-

**Comment by sethjohnson1** [comment]
Nah it should be fine - the CSS is only written on those pages rather than
globally

**Comment by CenterNancy** [comment]
Great- let's "re-close" this puppy!

Nancy

On Apr 8, 2015, at 4:50 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Nah it should be fine - the CSS is only written on those pages rather than
globally

On Wed, Apr 8, 2015 at 4:49 PM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I should've named more specifically then right? I was just in a hurry to
> see if it would work at all
>
> Nancy
>
> On Apr 8, 2015, at 4:47 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
>
>
> I think we're all set, just keep in mind you'll want to use the same class
> names if you intend to use it again
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/sethjohnson1/qr-pub/issues/90#issuecomment-91058407>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/qr-pub/issues/90#issuecomment-91058904>.
>

-
