### ISSUE TITLE
museum logos

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#93]
What we really need are two separate image files - one with the icon and one with the text. Responsive design doesn't work otherwise - due to the variation in the length. This can be seen on the scorecard page now on large screen vs. small screen

**Comment by sethjohnson1** [comment]
not perfect but it works. Divided the amount of each image by the widest one and used a percentage

**Comment by CenterNancy** [comment]
If the fixed width images we talked about me doing in photoshop would work better just let me know and I can do that!

Nancy

**Comment by sethjohnson1** [comment]
Not necessary - if we were doing an undetermined amount I might find a
better way but this looks fine (the CSS is just very specific to the width
of each image, typically I like things to be a little more generic)
