### ISSUE TITLE
deploy local iScout with admin and disable in production

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/qr-pub#94]
also hide the "SuperAdmin!" button

**Comment by sethjohnson1** [comment]
wow I just realized how epic this is going to be... the file uploads being the biggest problem. Perhaps the thing to do is have a Firewalled port on the existing server. . . . or use SFTP, not sure

**Comment by sethjohnson1** [comment]
there isn't really a good way to make this work, instead I used an IP whitelist. Not the ideal solution, but seemingly as secure as a local deployment connected to the remote server

**Comment by CenterNancy** [comment]
So is the correct admin section http://iscout.bbcw.org/admin/ (just want to make sure I’m working in the right place!)

Nancy

**Comment by sethjohnson1** [comment]
Yeeeeah
