### ISSUE TITLE
Check tests/templates done for instruction creation to "Inactive"

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#96]

**Comment by sethjohnson1** [comment]
Wow maybe it's too early but I have no idea what that means :)

**Comment by CenterNancy** [comment]
Ha! Yes it reads weird but I knew what I meant at the time :). Don't worry about it!

**Comment by CenterNancy** [comment]
Unchecked "Active" on test templates and those created to learn system.
