### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/qr-pub#97]
Not sure what - but need something.
Something based on the round Scout image?
Ask Desiree to work her magic for us?

**Comment by CenterNancy** [comment]
Graphics working on this - should have something for us by end of next week (3/13)

**Comment by CenterNancy** [comment]
Courtesy Graphics, attached are full icon and a favicon (not yet sized; this one is 400 x 400px)
![iscout-icon-black](https://cloud.githubusercontent.com/assets/9464698/6627970/82a334c0-c8c7-11e4-9d36-91ca56b80293.png)
![iscout-favicon-black](https://cloud.githubusercontent.com/assets/9464698/6627980/85941b72-c8c7-11e4-82ff-fa13c5867624.png)

**Comment by sethjohnson1** [comment]
cool. good work! Check it out (might need to hard refresh) and feel free to close the issue when you're ready

**Comment by CenterNancy** [comment]
Yay! A cool "ico" converter helped with this: http://iconverticons.com/online/
